import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  // Declarations are generated by `tsc -p tsconfig.build.json`; tsup's bundled
  // dts builder hard-codes a deprecated `baseUrl`, which breaks under TS 6+.
  dts: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'node20',
  outDir: 'dist',
});
